[project]
name = "DataSquash"
authors = [
    {name = "Adam Tyson", email = "code@adamltyson.com"},
    {name = "Niko Sirmpilatze", email = "niko.sirbiladze@gmail.com"},
    {name = "Joe Ziminski", email = "j.ziminski@ucl.ac.uk"},
]
description = "Data compression utilities for systems neuroscience."
readme = "README.md"
requires-python = ">=3.9.0"
dynamic = ["version"]

license = {text = "BSD-3-Clause"}

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: BSD License",
]

[project.urls]
"Homepage" = "https://github.com/neuroinformatics-unit/DataSquash"
"Bug Tracker" = "https://github.com/neuroinformatics-unit/DataSquash/issues"
"Documentation" = "https://neuroinformatics-unit.github.io/DataSquash"

"Source Code" = "https://github.com/neuroinformatics-unit/DataSquash"
"User Support" = "https://github.com/neuroinformatics-unit/DataSquash/issues"

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "coverage",
  "tox",
  "black",
  "mypy",
  "pre-commit",
  "ruff",
  "setuptools_scm",
]

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["datasquash*"]
exclude = ["tests", "docs*"]


[tool.pytest.ini_options]
addopts = "--cov=datasquash"

[tool.black]
target-version = ['py39', 'py310', 'py311']
skip-string-normalization = false
line-length = 88

[tool.setuptools_scm]

[tool.check-manifest]
ignore = [
  ".yaml",
  "tox.ini",
  "tests/",
  "tests/test_unit/",
  "tests/test_integration/",
  "docs/",
  "docs/source/",
]


[tool.ruff]
line-length = 88
exclude = ["__init__.py","build",".eggs"]
select = ["I", "E", "F"]
fix = true

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-*"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.tox]
legacy_tox_ini = """
[tox]
requires = tox-conda
envlist = py{39,310,311}
isolated_build = True

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
conda_deps =
    ffmpeg
conda_channels =
    conda-forge
extras =
    dev
commands =
    pytest -v --color=yes --cov=datasquash --cov-report=xml
"""
