VIDEO_DIR = "/Users/sofia/swc/project_DataSquash_video/datasets/drosophila-melanogaster-courtship/"
OUTPUT_DIR = "output/"

import os
VIDEO_FILES =  [
    f for f in os.listdir(VIDEO_DIR)
    if f.endswith('.mp4')
]

rule all:
    input:
        expand(
            "{output_dir}/log_{filename}.txt",
            filename=VIDEO_FILES,
            output_dir=OUTPUT_DIR
        )

rule video_encoding:
    input:
        video = "/Users/sofia/swc/project_DataSquash_video/datasets/drosophila-melanogaster-courtship/{filename}",
    output:
        encoded_video = "{output_dir}/log_{filename}.txt"
    shell:
        "ffprobe -v error -show_streams {input.video} > {output.encoded_video}"
